// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	pkg "git.iu7.bmstu.ru/mis21u869/PPO/-/tree/lab3/pkg"
	gomock "github.com/golang/mock/gomock"
)

// MockIUserRepo is a mock of IUserRepo interface.
type MockIUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIUserRepoMockRecorder
}

// MockIUserRepoMockRecorder is the mock recorder for MockIUserRepo.
type MockIUserRepoMockRecorder struct {
	mock *MockIUserRepo
}

// NewMockIUserRepo creates a new mock instance.
func NewMockIUserRepo(ctrl *gomock.Controller) *MockIUserRepo {
	mock := &MockIUserRepo{ctrl: ctrl}
	mock.recorder = &MockIUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserRepo) EXPECT() *MockIUserRepoMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockIUserRepo) CreateUser(user pkg.User) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", user)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockIUserRepoMockRecorder) CreateUser(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockIUserRepo)(nil).CreateUser), user)
}

// GetPasswordByID mocks base method.
func (m *MockIUserRepo) GetPasswordByID(id int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPasswordByID", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPasswordByID indicates an expected call of GetPasswordByID.
func (mr *MockIUserRepoMockRecorder) GetPasswordByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPasswordByID", reflect.TypeOf((*MockIUserRepo)(nil).GetPasswordByID), id)
}

// GetUserByEmail mocks base method.
func (m *MockIUserRepo) GetUserByEmail(email string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", email)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockIUserRepoMockRecorder) GetUserByEmail(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockIUserRepo)(nil).GetUserByEmail), email)
}

// MockIHomeRepo is a mock of IHomeRepo interface.
type MockIHomeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIHomeRepoMockRecorder
}

// MockIHomeRepoMockRecorder is the mock recorder for MockIHomeRepo.
type MockIHomeRepoMockRecorder struct {
	mock *MockIHomeRepo
}

// NewMockIHomeRepo creates a new mock instance.
func NewMockIHomeRepo(ctrl *gomock.Controller) *MockIHomeRepo {
	mock := &MockIHomeRepo{ctrl: ctrl}
	mock.recorder = &MockIHomeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHomeRepo) EXPECT() *MockIHomeRepoMockRecorder {
	return m.recorder
}

// CreateHome mocks base method.
func (m *MockIHomeRepo) CreateHome(idUser int, home pkg.Home) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHome", idUser, home)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateHome indicates an expected call of CreateHome.
func (mr *MockIHomeRepoMockRecorder) CreateHome(idUser, home interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHome", reflect.TypeOf((*MockIHomeRepo)(nil).CreateHome), idUser, home)
}

// DeleteHome mocks base method.
func (m *MockIHomeRepo) DeleteHome(idUser int, home pkg.Home) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHome", idUser, home)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHome indicates an expected call of DeleteHome.
func (mr *MockIHomeRepoMockRecorder) DeleteHome(idUser, home interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHome", reflect.TypeOf((*MockIHomeRepo)(nil).DeleteHome), idUser, home)
}

// UpdateHome mocks base method.
func (m *MockIHomeRepo) UpdateHome(idUser int, home pkg.Home) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHome", idUser, home)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateHome indicates an expected call of UpdateHome.
func (mr *MockIHomeRepoMockRecorder) UpdateHome(idUser, home interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHome", reflect.TypeOf((*MockIHomeRepo)(nil).UpdateHome), idUser, home)
}

// MockIAccessHomeRepo is a mock of IAccessHomeRepo interface.
type MockIAccessHomeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIAccessHomeRepoMockRecorder
}

// MockIAccessHomeRepoMockRecorder is the mock recorder for MockIAccessHomeRepo.
type MockIAccessHomeRepoMockRecorder struct {
	mock *MockIAccessHomeRepo
}

// NewMockIAccessHomeRepo creates a new mock instance.
func NewMockIAccessHomeRepo(ctrl *gomock.Controller) *MockIAccessHomeRepo {
	mock := &MockIAccessHomeRepo{ctrl: ctrl}
	mock.recorder = &MockIAccessHomeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAccessHomeRepo) EXPECT() *MockIAccessHomeRepoMockRecorder {
	return m.recorder
}

// AddUser mocks base method.
func (m *MockIAccessHomeRepo) AddUser(access pkg.AccessHome) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", access)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddUser indicates an expected call of AddUser.
func (mr *MockIAccessHomeRepoMockRecorder) AddUser(access interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockIAccessHomeRepo)(nil).AddUser), access)
}

// DeleteUser mocks base method.
func (m *MockIAccessHomeRepo) DeleteUser(idUser int, access pkg.AccessHome) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", idUser, access)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockIAccessHomeRepoMockRecorder) DeleteUser(idUser, access interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockIAccessHomeRepo)(nil).DeleteUser), idUser, access)
}

// GetListUserHome mocks base method.
func (m *MockIAccessHomeRepo) GetListUserHome(idHome int, access pkg.AccessHome) ([]pkg.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListUserHome", idHome, access)
	ret0, _ := ret[0].([]pkg.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListUserHome indicates an expected call of GetListUserHome.
func (mr *MockIAccessHomeRepoMockRecorder) GetListUserHome(idHome, access interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListUserHome", reflect.TypeOf((*MockIAccessHomeRepo)(nil).GetListUserHome), idHome, access)
}

// UpdateLevel mocks base method.
func (m *MockIAccessHomeRepo) UpdateLevel(idUser int, access pkg.AccessHome) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLevel", idUser, access)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLevel indicates an expected call of UpdateLevel.
func (mr *MockIAccessHomeRepoMockRecorder) UpdateLevel(idUser, access interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLevel", reflect.TypeOf((*MockIAccessHomeRepo)(nil).UpdateLevel), idUser, access)
}

// UpdateStatus mocks base method.
func (m *MockIAccessHomeRepo) UpdateStatus(idUser int, access pkg.AccessHome) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", idUser, access)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockIAccessHomeRepoMockRecorder) UpdateStatus(idUser, access interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockIAccessHomeRepo)(nil).UpdateStatus), idUser, access)
}

// MockIDeviceRepo is a mock of IDeviceRepo interface.
type MockIDeviceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIDeviceRepoMockRecorder
}

// MockIDeviceRepoMockRecorder is the mock recorder for MockIDeviceRepo.
type MockIDeviceRepoMockRecorder struct {
	mock *MockIDeviceRepo
}

// NewMockIDeviceRepo creates a new mock instance.
func NewMockIDeviceRepo(ctrl *gomock.Controller) *MockIDeviceRepo {
	mock := &MockIDeviceRepo{ctrl: ctrl}
	mock.recorder = &MockIDeviceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDeviceRepo) EXPECT() *MockIDeviceRepoMockRecorder {
	return m.recorder
}

// AddHomeDevice mocks base method.
func (m *MockIDeviceRepo) AddHomeDevice(idHome, idDevice int, input *pkg.Devices) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddHomeDevice", idHome, idDevice, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddHomeDevice indicates an expected call of AddHomeDevice.
func (mr *MockIDeviceRepoMockRecorder) AddHomeDevice(idHome, idDevice, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHomeDevice", reflect.TypeOf((*MockIDeviceRepo)(nil).AddHomeDevice), idHome, idDevice, input)
}

// CreateDevice mocks base method.
func (m *MockIDeviceRepo) CreateDevice(device *pkg.Devices) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDevice", device)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDevice indicates an expected call of CreateDevice.
func (mr *MockIDeviceRepoMockRecorder) CreateDevice(device interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDevice", reflect.TypeOf((*MockIDeviceRepo)(nil).CreateDevice), device)
}

// DeleteDevice mocks base method.
func (m *MockIDeviceRepo) DeleteDevice(idDevice int, device *pkg.Devices) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDevice", idDevice, device)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDevice indicates an expected call of DeleteDevice.
func (mr *MockIDeviceRepoMockRecorder) DeleteDevice(idDevice, device interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDevice", reflect.TypeOf((*MockIDeviceRepo)(nil).DeleteDevice), idDevice, device)
}

// DeleteHomeDevice mocks base method.
func (m *MockIDeviceRepo) DeleteHomeDevice(idHome, idDevice int, input *pkg.Devices) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHomeDevice", idHome, idDevice, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHomeDevice indicates an expected call of DeleteHomeDevice.
func (mr *MockIDeviceRepoMockRecorder) DeleteHomeDevice(idHome, idDevice, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHomeDevice", reflect.TypeOf((*MockIDeviceRepo)(nil).DeleteHomeDevice), idHome, idDevice, input)
}

// UpdateDevice mocks base method.
func (m *MockIDeviceRepo) UpdateDevice(idDevice int, device *pkg.Devices) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDevice", idDevice, device)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDevice indicates an expected call of UpdateDevice.
func (mr *MockIDeviceRepoMockRecorder) UpdateDevice(idDevice, device interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDevice", reflect.TypeOf((*MockIDeviceRepo)(nil).UpdateDevice), idDevice, device)
}

// MockIHistoryDeviceRepo is a mock of IHistoryDeviceRepo interface.
type MockIHistoryDeviceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIHistoryDeviceRepoMockRecorder
}

// MockIHistoryDeviceRepoMockRecorder is the mock recorder for MockIHistoryDeviceRepo.
type MockIHistoryDeviceRepoMockRecorder struct {
	mock *MockIHistoryDeviceRepo
}

// NewMockIHistoryDeviceRepo creates a new mock instance.
func NewMockIHistoryDeviceRepo(ctrl *gomock.Controller) *MockIHistoryDeviceRepo {
	mock := &MockIHistoryDeviceRepo{ctrl: ctrl}
	mock.recorder = &MockIHistoryDeviceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHistoryDeviceRepo) EXPECT() *MockIHistoryDeviceRepoMockRecorder {
	return m.recorder
}

// CreateDeviceHistory mocks base method.
func (m *MockIHistoryDeviceRepo) CreateDeviceHistory(history pkg.DevicesHistory) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeviceHistory", history)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDeviceHistory indicates an expected call of CreateDeviceHistory.
func (mr *MockIHistoryDeviceRepoMockRecorder) CreateDeviceHistory(history interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeviceHistory", reflect.TypeOf((*MockIHistoryDeviceRepo)(nil).CreateDeviceHistory), history)
}

// GetDeviceHistory mocks base method.
func (m *MockIHistoryDeviceRepo) GetDeviceHistory(idDevice int) ([]pkg.DevicesHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceHistory", idDevice)
	ret0, _ := ret[0].([]pkg.DevicesHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceHistory indicates an expected call of GetDeviceHistory.
func (mr *MockIHistoryDeviceRepoMockRecorder) GetDeviceHistory(idDevice interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceHistory", reflect.TypeOf((*MockIHistoryDeviceRepo)(nil).GetDeviceHistory), idDevice)
}

// UpdateDeviceHistory mocks base method.
func (m *MockIHistoryDeviceRepo) UpdateDeviceHistory(idDevice int, history pkg.DevicesHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeviceHistory", idDevice, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDeviceHistory indicates an expected call of UpdateDeviceHistory.
func (mr *MockIHistoryDeviceRepoMockRecorder) UpdateDeviceHistory(idDevice, history interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeviceHistory", reflect.TypeOf((*MockIHistoryDeviceRepo)(nil).UpdateDeviceHistory), idDevice, history)
}
