version: "3.5"

services:
  db:
    image: postgres:15.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Smena
      - POSTGRES_USER=Misfio32
    volumes:
      - type: bind
        source: /Users/ivanmamvriyskiy/Desktop/PPO/postgresData
        target: /mnt
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 3s
      retries: 5

  server:
    image: my-golang-server
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
